### ISSUE TITLE
Won't Install (Any version Blender?)

### ISSUE THREAD

**Issue by fewerjunk** [portnov/sverchok-extra#27]
I've tried installing it from the sverchok_extra_master zip file.  Renaming it to sverchok_master.  Renaming Sverchok to sverchok_bak and renaming sverchok_extra_master to sverchok.  Under 2.83.5, 2.9.0 (final), and 2.79.

Here's one error I get:

![SVE_Iinstall_error_JPG](https://user-images.githubusercontent.com/70761456/92245179-d11c4b00-ee78-11ea-89fb-f2dd53c7f620.jpg)

I'd really love to use it. But, so far, stuck.

**Comment by portnov** [comment]
Do you have Sverchok installed?
on the screenshot it's marked with an exclamation mark, is it working?

**Comment by fewerjunk** [comment]
I put it back the way it was (2.90) - Final
:
![sverchok_installed_JPG](https://user-images.githubusercontent.com/70761456/92251454-bd291700-ee81-11ea-826c-565cac03fdf2.jpg)

![sverchok_iextras_error_nstalled_JPG](https://user-images.githubusercontent.com/70761456/92251449-bb5f5380-ee81-11ea-95fe-decf6a76cd70.jpg)

**Comment by portnov** [comment]
Well, theoretically Sverchok-Extra should be installable without scipy, so I'll have to fix this.
However, in practice, almost all nodes in Sverchok-Extra use scipy.

So, please navigate to Sverchok preferences / Extra nodes and install scipy library (see also https://github.com/nortikin/sverchok/wiki/Dependencies). After that activate Sverchok-Extra.

**Comment by portnov** [comment]
Also, I have to say, at the moment Sverchok-Extra contains a few nodes (see Readme for actual list). A huge list of nodes was moved into core Sverchok some time ago.

**Comment by fewerjunk** [comment]
> Also, I have to say, at the moment Sverchok-Extra contains a few nodes (see Readme for actual list). A huge list of nodes was moved into core Sverchok some time ago.

Good to know.  Do the Examples work with Sverchok?

**Comment by portnov** [comment]
I tried to preserve compatibility. If jsons do not import, try to re-create them from screenshots where available.

**Comment by fewerjunk** [comment]
Still having problems.

Haven't tried the examples yet.

![F762573F-2FC5-4F78-A8C5-91863EB43194](https://user-images.githubusercontent.com/70761456/92257246-bf8f6f00-ee89-11ea-8cbe-203a48e48046.jpeg)

![B561B488-1AA2-4BBF-A73A-EB836CF40BC6](https://user-images.githubusercontent.com/70761456/92257247-c0280580-ee89-11ea-9dca-9de0ae124578.jpeg)

**Comment by portnov** [comment]
It's `python -m pip`, not `pip3`.
For Blender, you usually have to run Python from Blender's folder. Maybe at Macos Blender is using system-wide python installation, idk.

**Comment by fewerjunk** [comment]
Tried Gallery 1  (I think it's a problem with SciKit)

Example:

![7E4E0A7B-DD04-4D78-A425-F835BE8AF889](https://user-images.githubusercontent.com/70761456/92260738-3c701800-ee8d-11ea-9033-b6e8f2fea6f7.jpeg)

**Comment by fewerjunk** [comment]
Everything installed using "python -m pip".  Tried using "python -m pip3" just to see if there was a difference.  You're right pip3 didn't work, "python -m pip" did.

**Comment by fewerjunk** [comment]
> Everything installed using "python -m pip". Tried using "python -m pip3" just to see if there was a difference. You're right pip3 didn't work, "python -m pip" did.

**Comment by fewerjunk** [comment]
> It's `python -m pip`, not `pip3`.
> For Blender, you usually have to run Python from Blender's folder. Maybe at Macos Blender is using system-wide python installation, idk.

Installed from Blender folder using "python -m pip".

**Comment by fewerjunk** [comment]
Update.  Here's my pip list.  I think almost all dependencies (including scipy and scikit-image) are installed.
user@MacBook-Pro MacOS % pip list
Package             Version
------------------- ---------
alembic             1.3.1
antiprism-python    0.1.3
appdirs             1.4.3
beautifulsoup4      4.7.1
bottle              0.12.18
bottle-websocket    0.2.9
bs4                 0.0.1
certifi             2020.6.20
chardet             3.0.4
circlify            0.12.1
click               7.1.2
colorama            0.4.1
cssselect           1.1.0
cycler              0.10.0
Cython              0.29.21
decorator           4.4.2
Eel                 0.11.1
feedfinder2         0.0.4
feedparser          5.2.1
future              0.18.2
geomdl              5.3.0
gevent              20.6.2
gevent-websocket    0.10.1
greenlet            0.4.16
idna                2.10
imageio             2.9.0
imgurpython         1.1.7
jieba3k             0.35.1
joblib              0.16.0
kiwisolver          1.2.0
lxml                4.5.2
Mako                1.1.3
MarkupSafe          1.1.1
matplotlib          3.3.1
networkx            2.5
newspaper3k         0.2.8
nltk                3.5
numpy               1.19.1
pathvalidate        0.28.1
Pillow              7.2.0
pip                 20.2.2
praw                7.1.0
prawcore            1.5.0
psaw                0.0.12
PyMCubes            0.1.0
pyparsing           2.4.7
python-dateutil     2.8.1
python-editor       1.0.4
PyWavelets          1.1.1
PyYAML              5.3.1
regex               2020.7.14
requests            2.24.0
requests-file       1.5.1
scikit-image        0.17.2
scipy               1.5.2
setuptools          47.1.0
six                 1.15.0
soupsieve           2.0.1
SQLAlchemy          1.3.18
tifffile            2020.9.3
tinysegmenter       0.3
tldextract          2.2.3
tqdm                4.48.2
twitter-text-python 1.1.1
update-checker      0.18.0
urllib3             1.25.10
websocket-client    0.57.0
wheel               0.34.2
whichcraft          0.6.1
youtube-dl          2020.7.28
zope.event          4.4
zope.interface      5.1.0

**Comment by fewerjunk** [comment]
Just saw the MacOS Catalina threads under Sverchok.

So, I'm not the first.  Just the first here.

Tried another minimal surface example listed there.  Got it mostly working.  Used BMesh Viewer insted to get a mesh.

From there took a little effort to get a solid mesh going.

Nothing fancy but it makes the point:

![image](https://user-images.githubusercontent.com/70761456/92310242-4d8a5900-ef61-11ea-9ba2-b01d6b0c4069.png)

![image](https://user-images.githubusercontent.com/70761456/92310207-eff60c80-ef60-11ea-9fa7-e72a1d5d2852.png)
