### ISSUE TITLE
Error when trying to enable

### ISSUE THREAD

**Issue by agiac** [portnov/sverchok-extra#3]
When I tick on the flag to enable the add-on I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Alberto\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-extra-master\__init__.py", line 24, in <module>
    from sverchok.menu import SverchNodeItem, node_add_operators, SverchNodeCategory, register_node_panels, unregister_node_panels, unregister_node_add_operators, register_extra_category_provider
ImportError: cannot import name 'register_extra_category_provider' from 'sverchok.menu' (C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons_contrib\sverchok\menu.py)
```

I haven't installed all the dependencies of sverchok-extra because I am interested to try just a couple of nodes at the moment but I don't think that this is related.

I am using Blender 2.81a.

**Comment by portnov** [comment]
@AG89z for the moment you have to use the branch of Sverchok named "extra_adapt" to use Sverchok-extra.
I suspect that a managed to get the checkbox enabled in the preferences, then currently nodes should be available for you in the standard Blender's "Space" menu, but not in Sverchok's Shift-A menu, if you are not using "extra_adapt" branch.

I intend to get merged "extra_adapt" into master today or tomorrow...

**Comment by portnov** [comment]
@AG89z well, I merged extra_adapt, so now you can check out fresh Sverchok's master and fresh Sverchok-Extra's master, and they should work together...

**Comment by agiac** [comment]
Yes, works, thanks :)
