### ISSUE TITLE
Sverchok Extra add-on cannot start (blender-2.93.2)

### ISSUE THREAD

**Issue by rendetto** [portnov/sverchok-extra#37]
When trying to enable the add-on I got an error:

`Traceback (most recent call last):`
  `File "D:\BlenderBin\blender-2.93.2-candidate+v293.9e64fd461ac3-windows.amd64-release\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)`
  `File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\__init__.py", line 78, in <module>
    imported_modules = [icons] + make_node_list()`
  `File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\__init__.py", line 74, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)`
 `File "D:\BlenderBin\blender-2.93.2-candidate+v293.9e64fd461ac3-windows.amd64-release\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)`
  `File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\nodes\surface\triangular_mesh.py", line 7, in <module>
    from sverchok.core.update_system import process_from_node`
`ImportError: cannot import name 'process_from_node' from 'sverchok.core.update_system' (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py)`

**Comment by zeffii** [comment]
@rendetto  we can continue this here, because it sverchok-extra is not part of sverchok repository.

**Comment by zeffii** [comment]
we can initially make it support both sverchok 0.6.0 and 1.0.0, but for code simplification and maintainability dropping 0.6.0 makes more sense ( it's a rather niche user group)

**Comment by zeffii** [comment]
https://github.com/portnov/sverchok-extra/pull/41

**Comment by zeffii** [comment]
loads in latest sverchok. i'm not aware of any other breaking changes in Sverchok yet.
