### ISSUE TITLE
Install Pip windows 10 Pro  blender 2.83

### ISSUE THREAD

**Issue by BennyGovaerts** [portnov/sverchok-extra#4]
Can i install this with blender 2.83 ? or do i need blender 2.82 .. or must i change something  

![image](https://user-images.githubusercontent.com/49908008/73149215-7b044f80-40c0-11ea-943f-f2e03b65a04e.png)

**Comment by portnov** [comment]
I do not have much experience with windows... try this instruction: https://pip.pypa.io/en/stable/installing/ (you have to download get-pip.py and run it with  blender's python).

**Comment by BennyGovaerts** [comment]
I think we need some tutorials for how to install pip etc.... ,

**Comment by portnov** [comment]
probably... did that instruction help?

**Comment by BennyGovaerts** [comment]
For new users with no experience with python   this is to complex , there must be a better way to make this easy to install

**Comment by BennyGovaerts** [comment]
For example how to run get-pip.py with blender Python etc..

**Comment by portnov** [comment]
it should be something like
```
C:\> Blender\2.83\python\bin\python3.7.exe C:\Downloads\get-pip.py
```
:)

**Comment by portnov** [comment]
I also would like to have some kind of installer for several platforms, like launch -> next -> next -> finish... But I'm not sure how to it correctly for a Blender addon with dependencies, and also I don't have much time to support such installer for several platforms. If someone is willing to offer help, you're welcome! :)

**Comment by vicdoval** [comment]
This maybe useful https://github.com/s-leger/blender-pip?fbclid=IwAR3IfNz2ISwVkXUMcgU9Nhs6fJXLkXO3QZ2SeKGP_DDyjvOeTiOHDlBaoy8

**Comment by portnov** [comment]
I'm not sure it will help: it seem to use the same ensurepip
https://github.com/s-leger/blender-pip/blob/2d45cc4ca3481ea66860d9c5ee47eab73dd101ac/blender_pip.py#L78
which BennyGovaerts's python does not find for some reason...

**Comment by BennyGovaerts** [comment]
With cmd command prompt i can manual install pip and scikit-image , but this is way to difficult to use , and there are different version off numpy etc...  , 

So yeah we need a decent installer that can handle this

**Comment by portnov** [comment]
I've put some instructions about use of `get-pip.py` for pip installation into readme. Also now Sverchok-Extra has simple dependencies installation UI in the preferences. `scikit-image` and `scipy` can be installed from it nearly "in one click", once you've installed `pip`. For other dependencies, the dialog contains links to corresponding web sites.
