### ISSUE TITLE
Help！Cannot active the Sverchok-extra addon

### ISSUE THREAD

**Issue by 369386973** [portnov/sverchok-extra#50]
![20221125095400](https://user-images.githubusercontent.com/101614185/203884952-749426d2-5cdd-4e5c-8fef-5461a89b604f.jpg)
I have followed the README ，but it doesn't seem to work .

Thanks in advance!

**Comment by Durman** [comment]
You need last Sverchok version.

**Comment by 369386973** [comment]
> You need last Sverchok version.

Oh，it works！thx！
