### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok-extra#6]
![settings](https://user-images.githubusercontent.com/284644/74547121-74555380-4f6d-11ea-8388-80421a04fc3f.png)

**Comment by portnov** [comment]
![Screenshot_20200323_225227](https://user-images.githubusercontent.com/284644/77347101-27794f80-6d59-11ea-9bcd-182c918222cc.png)

![Screenshot_20200323_230108](https://user-images.githubusercontent.com/284644/77347798-344a7300-6d5a-11ea-88c2-e25e12be74b9.png)

**Comment by portnov** [comment]
![Screenshot_20200323_231848](https://user-images.githubusercontent.com/284644/77349405-cc495c00-6d5c-11ea-87bb-c1e83140f7bc.png)
![Screenshot_20200323_231942](https://user-images.githubusercontent.com/284644/77349410-cd7a8900-6d5c-11ea-8633-5cddd9d819bb.png)

**Comment by portnov** [comment]
![Screenshot_20200323_233118](https://user-images.githubusercontent.com/284644/77350494-6958c480-6d5e-11ea-8882-8679414bbfec.png)

**Comment by portnov** [comment]
![Screenshot_20200323_234049](https://user-images.githubusercontent.com/284644/77351539-bf7a3780-6d5f-11ea-8070-6ff58cdd7143.png)

**Comment by portnov** [comment]
NURBS approximation
![Screenshot_20200323_235702](https://user-images.githubusercontent.com/284644/77353015-09fcb380-6d62-11ea-8e69-e856e97dfdfc.png)

**Comment by portnov** [comment]
![Screenshot_20200324_201911](https://user-images.githubusercontent.com/284644/77443595-fc503800-6e0c-11ea-9340-6473785a6a51.png)
![Screenshot_20200324_202035](https://user-images.githubusercontent.com/284644/77443601-fd816500-6e0c-11ea-9ed2-0516eba95951.png)

**Comment by portnov** [comment]
![Screenshot_20200325_204331](https://user-images.githubusercontent.com/284644/77555651-50c0e980-6ed9-11ea-915f-8eb490c5904f.png)

**Comment by portnov** [comment]
![Screenshot_20200325_221221](https://user-images.githubusercontent.com/284644/77565225-ba46f500-6ee5-11ea-95ea-1baa8555d024.png)

**Comment by portnov** [comment]
![Screenshot_20200329_135626](https://user-images.githubusercontent.com/284644/77845087-6f6afd00-71c5-11ea-9062-77c195a512ce.png)
![Screenshot_20200329_135652](https://user-images.githubusercontent.com/284644/77845088-709c2a00-71c5-11ea-85a9-c090776c6c96.png)
![Screenshot_20200329_135833](https://user-images.githubusercontent.com/284644/77845090-7134c080-71c5-11ea-8c6b-10d04a95cf87.png)

**Comment by portnov** [comment]
![Screenshot_20200329_140607](https://user-images.githubusercontent.com/284644/77845220-8bbb6980-71c6-11ea-96f2-5e25bd8c36f1.png)
![Screenshot_20200329_140624](https://user-images.githubusercontent.com/284644/77845221-8cec9680-71c6-11ea-8f5a-1558b32a2e8b.png)
![Screenshot_20200329_140648](https://user-images.githubusercontent.com/284644/77845222-8d852d00-71c6-11ea-986c-0d7bbde0814d.png)

**Comment by portnov** [comment]
![Screenshot_20200329_142954](https://user-images.githubusercontent.com/284644/77845646-f4581580-71c9-11ea-9d16-b0ac95046441.png)
![Screenshot_20200329_143024](https://user-images.githubusercontent.com/284644/77845647-f5894280-71c9-11ea-95eb-b630c135dd7f.png)
![Screenshot_20200329_143111](https://user-images.githubusercontent.com/284644/77845648-f621d900-71c9-11ea-8000-31c2ddbd20ac.png)

**Comment by portnov** [comment]
![Screenshot_20200329_172517](https://user-images.githubusercontent.com/284644/77849062-473dc700-71e2-11ea-9722-c07fc32fda2c.png)
![Screenshot_20200329_173008](https://user-images.githubusercontent.com/284644/77849156-f8446180-71e2-11ea-9b46-fc2a4db63f29.png)

**Comment by portnov** [comment]
![Screenshot_20200329_174556](https://user-images.githubusercontent.com/284644/77849699-01cfc880-71e7-11ea-97b2-9229e0f9c630.png)
![Screenshot_20200329_175757](https://user-images.githubusercontent.com/284644/77849701-0300f580-71e7-11ea-89a7-197f7778da71.png)

**Comment by portnov** [comment]
![Screenshot_20200329_174242](https://user-images.githubusercontent.com/284644/77850952-6b53d500-71ef-11ea-80fe-07815a5c7e1d.png)

**Comment by portnov** [comment]
![Screenshot_20200329_212006](https://user-images.githubusercontent.com/284644/77854328-14f09180-7203-11ea-9192-028621be3d95.png)

**Comment by portnov** [comment]
![Screenshot_20200405_201514](https://user-images.githubusercontent.com/284644/78502370-470d7080-777a-11ea-9ee7-648946c89ab5.png)

**Comment by portnov** [comment]
![Screenshot_20200405_202129](https://user-images.githubusercontent.com/284644/78502538-12e67f80-777b-11ea-8ba6-d4d1d6360ce2.png)

**Comment by portnov** [comment]
![Screenshot_20200405_213711](https://user-images.githubusercontent.com/284644/78504334-eb48e480-7785-11ea-81cb-6987e67830b0.png)
![Screenshot_20200405_213916](https://user-images.githubusercontent.com/284644/78504337-ed12a800-7785-11ea-9a6c-1427ced45d55.png)

**Comment by portnov** [comment]
![Screenshot_20200405_214047](https://user-images.githubusercontent.com/284644/78504364-20edcd80-7786-11ea-831e-80db9be81e2b.png)

**Comment by portnov** [comment]
![Screenshot_20200405_223803](https://user-images.githubusercontent.com/284644/78505629-20593500-778e-11ea-998b-53b5b87925d3.png)

**Comment by portnov** [comment]
![Screenshot_20200405_225222](https://user-images.githubusercontent.com/284644/78506070-b8581e00-7790-11ea-9af1-2c3c84264dc8.png)
![Screenshot_20200405_225633](https://user-images.githubusercontent.com/284644/78506074-b9894b00-7790-11ea-9b5b-714a9fc79927.png)

**Comment by portnov** [comment]
![Screenshot_20200405_234907](https://user-images.githubusercontent.com/284644/78507210-3a981080-7798-11ea-84b8-d4e6e7d66803.png)

**Comment by portnov** [comment]
![Screenshot_20200406_000258](https://user-images.githubusercontent.com/284644/78507545-fdcd1900-7799-11ea-98d4-17bf8109396a.png)

**Comment by portnov** [comment]
![Screenshot_20200406_002043](https://user-images.githubusercontent.com/284644/78507901-792fca00-779c-11ea-90a7-e3c1cfecf39b.png)

**Comment by portnov** [comment]
![Screenshot_20200406_002630](https://user-images.githubusercontent.com/284644/78508072-987b2700-779d-11ea-9b53-6490db257aed.png)
![Screenshot_20200406_002845](https://user-images.githubusercontent.com/284644/78508073-99ac5400-779d-11ea-9a01-1d8824934ae4.png)

**Comment by portnov** [comment]
![Screenshot_20200406_004123](https://user-images.githubusercontent.com/284644/78508319-5ce15c80-779f-11ea-92a8-48e9ea65450c.png)

![Screenshot_20200406_004536](https://user-images.githubusercontent.com/284644/78508386-f6a90980-779f-11ea-9156-edd05500a0f8.png)

**Comment by portnov** [comment]
![Screenshot_20200407_221229](https://user-images.githubusercontent.com/284644/78699409-4b25c380-791d-11ea-8671-2b304e108ed1.png)
![Screenshot_20200407_221407](https://user-images.githubusercontent.com/284644/78699412-4bbe5a00-791d-11ea-87c9-78c7bbe4ed78.png)

**Comment by portnov** [comment]
![Screenshot_20200407_231253](https://user-images.githubusercontent.com/284644/78705373-cdff4c00-7926-11ea-943a-42eaa6ba8241.png)
![Screenshot_20200407_231649](https://user-images.githubusercontent.com/284644/78705377-cf307900-7926-11ea-8d30-9fd707c42ab6.png)

**Comment by portnov** [comment]
![Screenshot_20200414_212314](https://user-images.githubusercontent.com/284644/79249080-2dfd7180-7e96-11ea-810a-4a188536adc0.png)

**Comment by portnov** [comment]
![Screenshot_20200415_192254](https://user-images.githubusercontent.com/284644/79348542-8ee88080-7f4e-11ea-972b-50b9d6909734.png)

**Comment by portnov** [comment]
![Screenshot_20200415_195113](https://user-images.githubusercontent.com/284644/79351826-93169d00-7f52-11ea-99ad-bb904f62ce6c.png)

**Comment by portnov** [comment]
![Screenshot_20200415_200152](https://user-images.githubusercontent.com/284644/79353383-6cf1fc80-7f54-11ea-855b-ec782edf2c5f.png)
![Screenshot_20200415_200451](https://user-images.githubusercontent.com/284644/79353388-6e232980-7f54-11ea-87a8-b08d78ea34ff.png)

**Comment by portnov** [comment]
![Screenshot_20200415_203813](https://user-images.githubusercontent.com/284644/79357777-e5a78780-7f59-11ea-8f08-ba309965b67c.png)
![Screenshot_20200415_203914](https://user-images.githubusercontent.com/284644/79357785-e809e180-7f59-11ea-976a-a2bc32388ee0.png)
![Screenshot_20200415_204017](https://user-images.githubusercontent.com/284644/79357791-e93b0e80-7f59-11ea-9f8f-e74e1eead4cb.png)
![Screenshot_20200415_204346](https://user-images.githubusercontent.com/284644/79357796-eb04d200-7f59-11ea-8ef1-cb35ebb0083e.png)

**Comment by portnov** [comment]
![Screenshot_20200415_205327](https://user-images.githubusercontent.com/284644/79358827-2ce24800-7f5b-11ea-91ec-a5df4762e610.png)

**Comment by portnov** [comment]
![Screenshot_20200415_222723](https://user-images.githubusercontent.com/284644/79368209-771df600-7f68-11ea-9d65-90257d257bd0.png)
![Screenshot_20200415_222800](https://user-images.githubusercontent.com/284644/79368213-784f2300-7f68-11ea-80c0-059469ba14d9.png)

**Comment by portnov** [comment]
![Screenshot_20200415_223816](https://user-images.githubusercontent.com/284644/79369070-d0d2f000-7f69-11ea-97f6-b71d33f49b97.png)

**Comment by portnov** [comment]
![Screenshot_20200416_013448](https://user-images.githubusercontent.com/284644/79385737-83af4800-7f82-11ea-96e4-f4fb779646db.png)

**Comment by portnov** [comment]
![Screenshot_20200416_014048](https://user-images.githubusercontent.com/284644/79386265-50b98400-7f83-11ea-94bb-90d30a7c710a.png)

**Comment by portnov** [comment]
![Screenshot_20200416_014706](https://user-images.githubusercontent.com/284644/79387280-d558d200-7f84-11ea-9a28-68b5299ce8ec.png)
![Screenshot_20200416_015141](https://user-images.githubusercontent.com/284644/79387284-d689ff00-7f84-11ea-922f-bf28efcd7e53.png)

**Comment by vicdoval** [comment]
![image](https://user-images.githubusercontent.com/284644/79386265-50b98400-7f83-11ea-94bb-90d30a7c710a.png)
Should not have one more [ ] on each output? i think there are no nodes with a single [n] output

**Comment by portnov** [comment]
As far as I see, most of "measuring" nodes do add a [] (see Area, Path Length, etc). Also, all our nodes are vectorized: they usually work with lists of objects, not singular objects.

**Comment by portnov** [comment]
![Screenshot_20200416_200524](https://user-images.githubusercontent.com/284644/79472827-c07c4d00-801d-11ea-8ada-7494115955cc.png)

**Comment by portnov** [comment]
![Screenshot_20200416_202006](https://user-images.githubusercontent.com/284644/79474322-ae9ba980-801f-11ea-9cb0-0d6d5085e22a.png)

**Comment by portnov** [comment]
![Screenshot_20200416_202714](https://user-images.githubusercontent.com/284644/79475104-ad1eb100-8020-11ea-9974-172168c4bb4f.png)

![Screenshot_20200416_202829](https://user-images.githubusercontent.com/284644/79475246-dc352280-8020-11ea-8f8d-ddd3d6ca7a73.png)

**Comment by portnov** [comment]
![Screenshot_20200416_203719](https://user-images.githubusercontent.com/284644/79476391-5c0fbc80-8022-11ea-9457-1babe56f4388.png)
![Screenshot_20200416_203913](https://user-images.githubusercontent.com/284644/79476395-5d40e980-8022-11ea-846b-68da09ed2e41.png)

**Comment by portnov** [comment]
![Screenshot_20200416_222957](https://user-images.githubusercontent.com/284644/79487691-15c25980-8032-11ea-93e9-51f9b54bd36e.png)
![Screenshot_20200416_223148](https://user-images.githubusercontent.com/284644/79487695-16f38680-8032-11ea-9ea9-f1dea478d9cc.png)

![Screenshot_20200416_223435](https://user-images.githubusercontent.com/284644/79487987-7b164a80-8032-11ea-8197-c78314843ffa.png)

**Comment by portnov** [comment]
![Screenshot_20200416_224333](https://user-images.githubusercontent.com/284644/79488796-b8c7a300-8033-11ea-956c-fc66819a0aed.png)

**Comment by portnov** [comment]
![Screenshot_20200416_225712](https://user-images.githubusercontent.com/284644/79490196-ee6d8b80-8035-11ea-874a-1d126b5c46b1.png)
![Screenshot_20200416_225835](https://user-images.githubusercontent.com/284644/79490204-ef9eb880-8035-11ea-810d-59f9a98ebd5f.png)

**Comment by portnov** [comment]
![Screenshot_20200416_231143](https://user-images.githubusercontent.com/284644/79491540-0a722c80-8038-11ea-914f-0221e5e75f68.png)
![Screenshot_20200416_231422](https://user-images.githubusercontent.com/284644/79491547-0ba35980-8038-11ea-89fc-063982ea65cd.png)

**Comment by portnov** [comment]
![Screenshot_20200417_002109](https://user-images.githubusercontent.com/284644/79497591-60979d80-8041-11ea-9c23-1e0d6be96708.png)

**Comment by portnov** [comment]
![Screenshot_20200417_002406](https://user-images.githubusercontent.com/284644/79497828-cbe16f80-8041-11ea-957f-54c011afe3a3.png)

**Comment by portnov** [comment]
![Screenshot_20200417_005056](https://user-images.githubusercontent.com/284644/79501153-08fc3080-8047-11ea-818e-374309637dfe.png)

**Comment by vicdoval** [comment]
> As far as I see, most of "measuring" nodes do add a [] (see Area, Path Length, etc). Also, all our nodes are vectorized: they usually work with lists of objects, not singular objects.

You mean this node is not vectorized? anyway to me looks more proper if the outputs is [[n]]
![image](https://user-images.githubusercontent.com/10011941/79514624-ee29bc00-8046-11ea-96a2-ec7a853a0c7a.png)
(The volume node i think it should do it too....)

**Comment by portnov** [comment]
So, the node should add another pair of []. Ok, will do.

**Comment by portnov** [comment]
![Screenshot_20200418_003705](https://user-images.githubusercontent.com/284644/79607518-c309a000-810c-11ea-86fa-be7c16043b32.png)

**Comment by portnov** [comment]
![Screenshot_20200418_011250](https://user-images.githubusercontent.com/284644/79610315-bdfb1f80-8111-11ea-886d-030538a50e5d.png)

**Comment by portnov** [comment]
![Screenshot_20200418_011335](https://user-images.githubusercontent.com/284644/79610367-d834fd80-8111-11ea-9d3b-95b671256904.png)

**Comment by portnov** [comment]
![Screenshot_20200419_212412](https://user-images.githubusercontent.com/284644/79693501-75b03e80-8284-11ea-841b-9b5911bf91e7.png)

![Screenshot_20200419_231136](https://user-images.githubusercontent.com/284644/79695949-29202f80-8293-11ea-8623-1df67c3a68ef.png)

**Comment by portnov** [comment]
![Screenshot_20240915_130138](https://github.com/user-attachments/assets/8b31fa7f-e46c-4769-aa5b-d42f7005d969)
![Screenshot_20240915_125813](https://github.com/user-attachments/assets/e42ad3d9-6fa3-41c9-8646-7f90604d951e)
