### ISSUE TITLE
PyMCubes didn't install

### ISSUE THREAD

**Issue by unkerjay** [portnov/sverchok-extra#7]
Everything else did as directed.

hometp@hometp-ThinkPad-W530 ~ $ /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/bin/python3.7m -m pip install -U PyMCubes

Collecting PyMCubes
  Using cached PyMCubes-0.0.12.tar.gz (12 kB)
Building wheels for collected packages: PyMCubes
  Building wheel for PyMCubes (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/bin/python3.7m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-913_1mdh
       cwd: /tmp/pip-install-cbc8axsz/PyMCubes/
  Complete output (19 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/mcubes
  copying mcubes/exporter.py -> build/lib.linux-x86_64-3.7/mcubes
  copying mcubes/__init__.py -> build/lib.linux-x86_64-3.7/mcubes
  running build_ext
  building 'mcubes._mcubes' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/mcubes
  creating build/temp.linux-x86_64-3.7/mcubes/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sergey/Developer/build_linux/deps/Release/sqlite/include -I/home/sergey/Developer/build_linux/deps/Release/bzip2/include -I/home/sergey/Developer/build_linux/deps/Release/lzma/include -I/home/sergey/Developer/build_linux/deps/Release/zlib/include -fPIC -fPIC -Imcubes/src -I/home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/lib/python3.7/site-packages/numpy/core/include -I/home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/include/python3.7m -c mcubes/src/_mcubes.cpp -o build/temp.linux-x86_64-3.7/mcubes/src/_mcubes.o -std=c++11 -Wall
  mcubes/src/_mcubes.cpp:35:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyMCubes
  Running setup.py clean for PyMCubes
Failed to build PyMCubes
Installing collected packages: PyMCubes
    Running setup.py install for PyMCubes ... error
    ERROR: Command errored out with exit status 1:
     command: /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/bin/python3.7m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l7ioj6k3/install-record.txt --single-version-externally-managed --compile --install-headers /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/include/python3.7m/PyMCubes
         cwd: /tmp/pip-install-cbc8axsz/PyMCubes/
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/mcubes
    copying mcubes/exporter.py -> build/lib.linux-x86_64-3.7/mcubes
    copying mcubes/__init__.py -> build/lib.linux-x86_64-3.7/mcubes
    running build_ext
    building 'mcubes._mcubes' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/mcubes
    creating build/temp.linux-x86_64-3.7/mcubes/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sergey/Developer/build_linux/deps/Release/sqlite/include -I/home/sergey/Developer/build_linux/deps/Release/bzip2/include -I/home/sergey/Developer/build_linux/deps/Release/lzma/include -I/home/sergey/Developer/build_linux/deps/Release/zlib/include -fPIC -fPIC -Imcubes/src -I/home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/lib/python3.7/site-packages/numpy/core/include -I/home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/include/python3.7m -c mcubes/src/_mcubes.cpp -o build/temp.linux-x86_64-3.7/mcubes/src/_mcubes.o -std=c++11 -Wall
    mcubes/src/_mcubes.cpp:35:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/bin/python3.7m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cbc8axsz/PyMCubes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l7ioj6k3/install-record.txt --single-version-externally-managed --compile --install-headers /home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/include/python3.7m/PyMCubes Check the logs for full command output.

**Comment by portnov** [comment]
Python's blender can't find your Python defevlopment files. Did you install something like `python-dev`? Try to locate `Python.h` file on your system and copy it and the whole folder into `/home/hometp/Downloads/Blender/282/final/blender-2.82-linux64/2.82/python/include/python3.7m/`

Also, PyMCubes is an optional dependency, sverchok-extra can work without it. If you need marching cubes, it will be probably simpler to install scikit-image.

**Comment by unkerjay** [comment]
scikit-image installed just fine.

If, as you say, PyMCube is optional and Marching Cubes works without it
(haven't tested it yet), you have, likely, I'm good.

**Comment by portnov** [comment]
Feel free to reopen if necessary.
